### ISSUE TITLE
Deprecated requirement

### ISSUE THREAD

**Issue by HumanG33k** [nodanaonlyzuul/asciiart#7]
W: `require 'RMagick'` is deprecated, please change to `require 'rmagick'`

(In the debian testing package)

**Comment by nodanaonlyzuul** [comment]
Hey @HumanG33k 

Thanks for filing the issue.
It's been a while since I've worked on this library - looks like this is a good excuse for me to do some cross-platform testing using continuous integration.

It will be another few days until I'll have the time and machine to do hands on testing in Ubuntu.
In the mean time, if you'd like to fork and file a pull request I'd take a look at it!

Thanks again - and sorry for the slow reply.

**Comment by caderaspindrift** [comment]
I threw in a quick pull request fixing this.

**Comment by nodanaonlyzuul** [comment]
Closed per https://github.com/nodanaonlyzuul/asciiart/issues/7
