### ISSUE TITLE
Piping coloured output to less removes color escape sequences

### ISSUE THREAD

**Issue by tpapastylianou** [nodanaonlyzuul/asciiart#8]
Example use:

    asciiart lena.jpg -c | less -R

Running the command without piping results in a beautiful coloured asciiart image in the terminal.
However, when piping is performed, only a normal monochromatic asciiart is generated, even though less is called with the -R command which would otherwise have enabled interpretation of escape sequences relating to colour.

In my opinion, the -c option should force outputting escape sequences and attempt no detection of color ability from the terminal, so that this choice is left up to the user.

**Comment by nodanaonlyzuul** [comment]
I'm able to replicate this. It happens with _any_ piping.

For example:

```shell
$ asciiart -c flanders.jpg
<COLOR ART HERE>

$ asciiart -c flanders.jpg | grep =
<white "="s here>
```

It's been a LOOONNNNNGGG time since this gem has gotten any attention so thanks for the issue.
I'm not proud of some of this code but....

-c (with text output relies on [the rainbow gem](https://github.com/sickill/rainbow) (v 2.0.0).
I see Rainbow has been updated to 3.0.0 since I originally wrote asciiart and maybe they're aware of it...or maybe it's a limitation of colored output? I'm no expect but I made a small test using Rainbow 2.0.0

```ruby

#rainbowtext.rb
require 'rainbow'
require 'rainbow/ext/string'

puts "Lorem ipsum dolor sit amet, consectetur adipisicing elit,
sed do eiusmod tempor incididunt ut labore et dolore magna
  aliqua. Ut enim ad minim veniam, quis ".color(:yellow)
```

```shell
$ ruby rainbowtest.rb
<YELLOW TEXT HERE>

$ ruby rainbowtest.rb | grep m
<white m's here>
```

When I have some freetime - I can experiment with newer versions of Rainbow, but if you have a moment you could try it to? The exact line is [here](https://github.com/nodanaonlyzuul/asciiart/blob/master/lib/asciiart.rb#L58).

You'd need to:

1.  Bump the gemspec to newer version of Rainbow
2. Use newer syntax if needed.

**Comment by tpapastylianou** [comment]
Thanks, Stephen!

I had a look inside rainbow.rb. It contains this line:

      self.enabled = true if ENV['CLICOLOR_FORCE'] == '1'

Therefore, this now works as intended:

    CLICOLOR_FORCE=1 asciiart -c imagefile.png | less -R

:)

**Comment by nodanaonlyzuul** [comment]
For sure - this has been a fun introduction (for me at least) about how color is managed in terminals. I've created https://github.com/nodanaonlyzuul/asciiart/issues/9 and will take a swing at it!
